### ISSUE TITLE
Erreur 500 quand on accède a une page inexistante dans un "dossier"

### ISSUE THREAD

**Issue by trpyn** [entropyqueen/trans-cec#16]
Basiquement l'url pattern matching va chercher à ce qu'il y ait toujours `/category/page/` 

Si on accède à une catégorie innexistante ou une page innexistante d'une catégorie, le serveur crash avec une erreur 500.

Par exemple ici:
```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/acaaaa/bb/

Django Version: 4.1.3
Python Version: 3.10.6
Installed Applications:
['django.contrib.staticfiles', 'django_tex', 'pdfgenerator']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/app/web/pdfgenerator/views.py", line 34, in form
    form_config = forms.REGISTERED_FORMS[form_id]

Exception Type: KeyError at /acaaaa/bb/
Exception Value: 'acaaaa_bb'
```

Il faut catch l'erreur et display un 404 à la place 
Cette issue va de pair avec #9  qui est basée sur le même concept.

**Comment by trpyn** [comment]
fixed by 78afe076106bfe17502db61b427fa083cd4eac8a
